trigger:
  branches:
    include:
    - master

name:  $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]
  REPOSITORY_NAME: $(Build.Repository.Name)
  COMMIT_TAG: $(git log --format=%h -1)

steps:
- script: |
     curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
     sudo apt update
     sudo apt install p7zip-full haveged
     sudo dpkg -i pacman.deb
     sudo dkp-pacman -Sy
     sudo dkp-pacman -S nds-dev --noconfirm
  displayName: 'Setup environment'

- script: |
    echo $(TRAVIS_COMMIT)
    echo $(COMMIT_TAG)
    echo $(BUILD_SOURCEVERSION)
  displayName: 'Echo Variables'
  
- script: |
     export DEVKITPRO="/opt/devkitpro"
     export DEVKITARM="/opt/devkitpro/devkitARM"
     chmod +x make_cia
     make
     export COMMIT_TAG="$(git log --format=%h -1)"
     export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
     mkdir Relaunch/
     mkdir Relaunch/Flashcart/
     mkdir Relaunch/3DS/
     mkdir Relaunch/DSi/
     mkdir Relaunch/DSi/_nds/
     mkdir Relaunch/3DS/_nds/
     mkdir Relaunch/Flashcart/_nds/
     mkdir Relaunch/DSi/_nds/Relaunch/
     mkdir Relaunch/3DS/_nds/Relaunch/
     mkdir Relaunch/Flashcart/_nds/Relaunch/
     mv './menu_Flashcart.bin' 'Relaunch/Flashcart/_nds/Relaunch/menu.bin'
     mv './Relaunch_Flashcart.nds' 'Relaunch/Flashcart/Relaunch.nds'
     mv './menu_3DS.bin' 'Relaunch/3DS/_nds/Relaunch/menu.bin'
     mv './Relaunch_3DS.cia' 'Relaunch/3DS/Relaunch.cia'
     mv './menu_DSi.bin' 'Relaunch/DSi/_nds/Relaunch/menu.bin'
     mv './Relaunch_DSi.nds' 'Relaunch/DSi/Relaunch.nds'
     7z a Relaunch.7z Relaunch/
     ls
  displayName: 'Build Relaunch'

- script: |    
    echo '##vso[task.setvariable variable=COMMIT_TAG]'$(git log --format=%h -1)
    echo '##vso[task.setvariable variable=COMMIT_MESSAGE]'$(git log --pretty=format:"%an - %s" -1)
    git config --global user.email "flamekat54@aol.com"
    git config --global user.name "TWLBot"
    git clone https://$GITHUB_TOKEN@github.com/Universal-Team/extras.git
    cd extras/builds/
    cp ../../Relaunch.7z Relaunch.7z
    git stage .
    git commit -m "Relaunch | $(COMMIT_TAG)"
    git push origin master
    git tag v$CURRENT_DATE
    echo '##vso[task.setvariable variable=TWLBOT_COMMIT]'$(git log -1 --format="%H")
  displayName: "Commit to Universal-Team/extras"

#- task: GitHubRelease@0
#  displayName: "Release to Universal-Team/extras"
#  inputs:
#    gitHubConnection: TWLBot
#    repositoryName: Universal-Team/extras
#    action: create
#    target: $(EXTRAS_COMMIT)
#    tagSource: 'manual'
#    tag: v$(CURRENT_DATE)
#    title: Relaunch | $(COMMIT_TAG)
#    releaseNotesSource: input
#    releaseNotes: $(COMMIT_MESSAGE)
#    assets: '$(Build.ArtifactStagingDirectory)/**/*'
#    isPreRelease: true
#    addChangeLog: false

- script: |
    curl -o send.sh https://raw.githubusercontent.com/DS-Homebrew/discord-webhooks/master/send-azure.sh
    chmod +x send.sh
    export IMAGE=https://raw.githubusercontent.com/Universal-Team/extras/v$CURRENT_DATE/pkmn-chest.png
    ./send.sh success $WEBHOOK_URL
  condition: succeeded()
  displayName: "Send success webhook"
- script: |
    curl -o send.sh https://raw.githubusercontent.com/DS-Homebrew/discord-webhooks/master/send-azure.sh
    chmod +x send.sh
    ./send.sh failure $WEBHOOK_URL
  condition: failed()
  displayName: "Send failure webhook"
